# Generated by Django 5.2.7 on 2025-10-17 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TB_CATEGORIAS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='TB_NACCESS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=20)),
                ('ADD_PRATO', models.BooleanField(default=False)),
                ('MOD_PRATO', models.BooleanField(default=False)),
                ('REM_PRATO', models.BooleanField(default=False)),
                ('ADD_PUBLI', models.BooleanField(default=False)),
                ('MOD_PUBLI', models.BooleanField(default=False)),
                ('REM_PUBLI', models.BooleanField(default=False)),
                ('ADD_DESTA', models.BooleanField(default=False)),
                ('REM_DESTA', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TB_PUBLICACOES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=45)),
                ('Texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TB_PRATOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=45)),
                ('Disponibilidade', models.BooleanField(default=True)),
                ('Preco', models.FloatField()),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tb_categorias')),
            ],
        ),
        migrations.CreateModel(
            name='TB_IMAGENS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imagem', models.ImageField(upload_to='publi/')),
                ('ID_Publicacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tb_publicacoes')),
            ],
        ),
        migrations.CreateModel(
            name='TB_USUARIOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=45)),
                ('CPF', models.CharField(max_length=11)),
                ('Email', models.CharField(max_length=45)),
                ('Login', models.CharField(max_length=45)),
                ('Senha', models.CharField(max_length=45)),
                ('N_Acesso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tb_naccess')),
            ],
        ),
    ]
