# Generated by Django 5.2.7 on 2025-10-17 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_usuarios',
            name='id',
        ),
        migrations.AlterField(
            model_name='tb_usuarios',
            name='CPF',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='TB_HISTORICO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Acao', models.CharField(max_length=50)),
                ('Data', models.DateTimeField()),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tb_usuarios')),
            ],
        ),
    ]
