# Generated by Django 5.2.4 on 2025-10-17 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_tb_usuarios_id_alter_tb_usuarios_cpf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_usuarios',
            name='N_Acesso',
        ),
        migrations.AddField(
            model_name='tb_usuarios',
            name='ADD_DESTA',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tb_usuarios',
            name='ADD_PRATO',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tb_usuarios',
            name='ADD_PUBLI',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tb_usuarios',
            name='MOD_PRATO',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tb_usuarios',
            name='MOD_PUBLI',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tb_usuarios',
            name='REM_DESTA',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tb_usuarios',
            name='REM_PRATO',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tb_usuarios',
            name='REM_PUBLI',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='TB_NACCESS',
        ),
    ]
