# Generated by Django 5.2.4 on 2025-10-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_tb_usuarios_n_acesso_tb_usuarios_add_desta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_pratos',
            name='Imagem',
            field=models.ImageField(blank=True, null=True, upload_to='pratos/'),
        ),
    ]
