# Generated by Django 5.2.4 on 2025-10-22 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tb_pratos_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TB_ACOMPANHAMENTOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=45)),
                ('Quantidade', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='tb_pratos',
            name='Acompanhamentos',
            field=models.ManyToManyField(blank=True, to='core.tb_acompanhamentos'),
        ),
    ]
