# Generated by Django 5.2.4 on 2025-10-22 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tb_acompanhamentos_tb_pratos_acompanhamentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_acompanhamentos',
            name='Quantidade',
        ),
    ]
