# Generated by Django 5.2.7 on 2025-10-22 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_tb_acompanhamentos_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_pratos',
            name='Acompanhamentos',
        ),
    ]
