# Generated by Django 5.2.7 on 2025-10-22 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_tb_pratos_acompanhamentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_acompanhamentos',
            name='ID_Prato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.tb_pratos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tb_acompanhamentos',
            name='Quantidade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
