# Generated by Django 5.2.4 on 2025-10-23 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tb_acompanhamentos_id_prato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_pratos',
            name='Categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tb_categorias'),
        ),
    ]
