# Generated by Django 5.2.4 on 2025-10-23 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_tb_pratos_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_acompanhamentos',
            name='ID_Prato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tb_pratos'),
        ),
        migrations.AlterField(
            model_name='tb_pratos',
            name='Categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tb_categorias'),
        ),
    ]
