# Generated by Django 5.2.4 on 2025-10-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_tb_acompanhamentos_id_prato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_usuarios',
            name='Email',
            field=models.EmailField(max_length=45),
        ),
    ]
