# Generated by Django 5.2.4 on 2025-10-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_tb_usuarios_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_pratos',
            name='Destaque',
            field=models.BooleanField(default=False),
        ),
    ]
