# Generated by Django 5.2.7 on 2025-10-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_tb_pratos_destaque'),
    ]

    operations = [
        migrations.CreateModel(
            name='TB_NEWSLETTER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Status', models.BooleanField(default=True)),
            ],
        ),
    ]
