# Generated by Django 5.2.4 on 2025-10-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_tb_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_pratos',
            name='Preco',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
