# Generated by Django 5.2.4 on 2025-10-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_tb_pratos_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_categorias',
            name='Ordem',
            field=models.IntegerField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
