# Generated by Django 5.2.4 on 2025-10-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_tb_categorias_ordem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_categorias',
            name='Ordem',
            field=models.IntegerField(),
        ),
    ]
