# Generated by Django 5.2.4 on 2025-10-30 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_tb_categorias_ordem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_imagens',
            name='ID_Publicacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tb_publicacoes'),
        ),
    ]
