# Generated by Django 5.2.4 on 2025-10-31 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_tb_imagens_id_publicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_publicacoes',
            name='Data',
            field=models.DateField(auto_now_add=True, default='2025-01-01'),
            preserve_default=False,
        ),
    ]
